build:
  version: 2016-03-14 # version of the build schema.
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile.builder
      artifacts:
        - /go/src/github.com/foldingbeauty/operator/operator
    production:
      name: operator:0.1.1
      dockerfile: Dockerfile.production
      depends_on:
        - builder