apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: miners.foldingbeauty.io
spec:
  version: v1
  group: foldingbeauty.io
  names:
    kind: Miner
    listKind: MinerList
    plural: miners
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
            kind:
              type: string
              enum:
                - bitcoin
                - litecoin
                - gulden
                - ether  