apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: miners.foldingbeauty.io
spec:
  group: foldingbeauty.io
  names:
    kind: Miner
    listKind: MinerList
    plural: miners
  scope: Namespaced
  version: v1