apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner-operator-deployment
  labels:
    app: miner-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miner-operator
  template:
    metadata:
      labels:
        app: miner-operator
    spec:
      containers:
      - name: miner-operator
        image: operator:0.1.3
        command: ["./operator","--logtostderr"]
        imagePullPolicy: Never
 