// Code generated by lister-gen. DO NOT EDIT.

package v1

// MinerListerExpansion allows custom methods to be added to
// MinerLister.
type MinerListerExpansion interface{}

// MinerNamespaceListerExpansion allows custom methods to be added to
// MinerNamespaceLister.
type MinerNamespaceListerExpansion interface{}
