// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/foldingbeauty/operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Miners returns a MinerInformer.
	Miners() MinerInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Miners returns a MinerInformer.
func (v *version) Miners() MinerInformer {
	return &minerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
