// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	foldingbeauty_io_v1 "github.com/foldingbeauty/operator/pkg/apis/foldingbeauty.io/v1"
	versioned "github.com/foldingbeauty/operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/foldingbeauty/operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/foldingbeauty/operator/pkg/client/listers/foldingbeauty.io/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MinerInformer provides access to a shared informer and lister for
// Miners.
type MinerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MinerLister
}

type minerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMinerInformer constructs a new informer for Miner type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMinerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMinerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMinerInformer constructs a new informer for Miner type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMinerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FoldingbeautyV1().Miners(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FoldingbeautyV1().Miners(namespace).Watch(options)
			},
		},
		&foldingbeauty_io_v1.Miner{},
		resyncPeriod,
		indexers,
	)
}

func (f *minerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMinerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *minerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&foldingbeauty_io_v1.Miner{}, f.defaultInformer)
}

func (f *minerInformer) Lister() v1.MinerLister {
	return v1.NewMinerLister(f.Informer().GetIndexer())
}
