// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	foldingbeauty_io_v1 "github.com/foldingbeauty/operator/pkg/apis/foldingbeauty.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMiners implements MinerInterface
type FakeMiners struct {
	Fake *FakeFoldingbeautyV1
	ns   string
}

var minersResource = schema.GroupVersionResource{Group: "foldingbeauty.io", Version: "v1", Resource: "miners"}

var minersKind = schema.GroupVersionKind{Group: "foldingbeauty.io", Version: "v1", Kind: "Miner"}

// Get takes name of the miner, and returns the corresponding miner object, and an error if there is any.
func (c *FakeMiners) Get(name string, options v1.GetOptions) (result *foldingbeauty_io_v1.Miner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(minersResource, c.ns, name), &foldingbeauty_io_v1.Miner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*foldingbeauty_io_v1.Miner), err
}

// List takes label and field selectors, and returns the list of Miners that match those selectors.
func (c *FakeMiners) List(opts v1.ListOptions) (result *foldingbeauty_io_v1.MinerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(minersResource, minersKind, c.ns, opts), &foldingbeauty_io_v1.MinerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &foldingbeauty_io_v1.MinerList{}
	for _, item := range obj.(*foldingbeauty_io_v1.MinerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested miners.
func (c *FakeMiners) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(minersResource, c.ns, opts))

}

// Create takes the representation of a miner and creates it.  Returns the server's representation of the miner, and an error, if there is any.
func (c *FakeMiners) Create(miner *foldingbeauty_io_v1.Miner) (result *foldingbeauty_io_v1.Miner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(minersResource, c.ns, miner), &foldingbeauty_io_v1.Miner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*foldingbeauty_io_v1.Miner), err
}

// Update takes the representation of a miner and updates it. Returns the server's representation of the miner, and an error, if there is any.
func (c *FakeMiners) Update(miner *foldingbeauty_io_v1.Miner) (result *foldingbeauty_io_v1.Miner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(minersResource, c.ns, miner), &foldingbeauty_io_v1.Miner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*foldingbeauty_io_v1.Miner), err
}

// Delete takes name of the miner and deletes it. Returns an error if one occurs.
func (c *FakeMiners) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(minersResource, c.ns, name), &foldingbeauty_io_v1.Miner{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMiners) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(minersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &foldingbeauty_io_v1.MinerList{})
	return err
}

// Patch applies the patch and returns the patched miner.
func (c *FakeMiners) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *foldingbeauty_io_v1.Miner, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(minersResource, c.ns, name, data, subresources...), &foldingbeauty_io_v1.Miner{})

	if obj == nil {
		return nil, err
	}
	return obj.(*foldingbeauty_io_v1.Miner), err
}
