// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/foldingbeauty/operator/pkg/client/clientset/versioned/typed/foldingbeauty.io/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeFoldingbeautyV1 struct {
	*testing.Fake
}

func (c *FakeFoldingbeautyV1) Miners(namespace string) v1.MinerInterface {
	return &FakeMiners{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeFoldingbeautyV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
